#baseurl: /blog # the subpath of your site, e.g. /blog
 # the base hostname & protocol for your site, e.g. http://example.com

# author:
# name: "emily lau"
# url: https://96emily.github.io

# Build settings
markdown: kramdown
highlighter: rouge
deploy: 
type: git
repository: git@github.com:96emily/96emily.github.io.git
branch: master
title: Test
url: git@github.com:96emily/96emily.github.io.git
baseurl: '/home'
#tagline: 
#permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
#paginate_path: "/page/:num"


# Pages Path
# defaults:
#   - scope:
#       path: '_pages'
#     values:
#       permalink: /:basename:output_ext

# include:
#   - _pages


# Tags
# tag_page_dir:         tag
# tag_page_layout:      tag_page
# tag_permalink_style:  pretty

# sass:
#   sass_dir: _sass
#   style: compressed

sidebar_home_link: true
